name             'opam'
maintainer       'Dave Parfitt'
maintainer_email 'dparfitt@chef.io'
license          'Apache v2.0'
description      'Installs/Configures OCaml opam packages'
long_description 'Installs/Configures OCaml opam packages'
version          '0.1.0'
